name: Snyk Infrastructure as Code check
on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
jobs:
  security:
    environment: snyk_env
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check Kubernetes manifest file for issues
        uses: snyk/actions/iac@master
        with:
          args: --report
